/run/initialize

/vis/open OGL 600x600-0+0

/vis/drawVolume

/vis/geometry/set/visibility World 0 false

/vis/viewer/set/style surface
/vis/viewer/set/viewpointThetaPhi 120 150
/vis/viewer/set/autoRefresh true


/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate 1000
/vis/scene/add/axes    
/vis/scene/add/eventID

/vis/scene/add/text 0 6 14 cm 18 4 4 Box
/vis/ogl/set/displayListLimit 50000

/run/beamOn 10
